numbers <- c(9, 23, 33, 91, 13)
players <- c("Ron Harper", "Michael Jordan", "Scottie Pippen", "Dennis Rodman", "Luc Longley")
df <- data.frame(number = numbers, player = players, stringsAsFactors = FALSE)
toni_kukoc <- data.frame(number = 7, player = "Toni Kukoc", stringsAsFactors = FALSE)
df <- rbind(df, toni_kukoc)
View(df)